CREATE TABLE "units" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_unit" varchar(100) NOT NULL,
  "alamat" varchar(255),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unit_id" integer,
  "nama" varchar(100) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "no_hp" varchar(20),
  "alamat" varchar(255),
  "role" enum(superadmin,guru,kepala_unit) NOT NULL,
  "gaji_pokok" decimal(12,2) DEFAULT 0,
  "tunjangan_kesehatan" decimal(12,2) DEFAULT 0,
  "tunjangan_transport" decimal(12,2) DEFAULT 0,
  "tunjangan_kerajinan" decimal(12,2) DEFAULT 0,
  "status" enum(aktif,nonaktif) DEFAULT 'aktif',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "kategori_murid" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kode_kategori" varchar(10) UNIQUE NOT NULL,
  "nama_kategori" varchar(50),
  "poin_progress" decimal(8,2) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "murid" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "unit_id" integer,
  "kategori_murid_id" integer,
  "nama_murid" varchar(100) NOT NULL,
  "status" enum(aktif,nonaktif) DEFAULT 'aktif',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "kehadiran" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "bulan" integer NOT NULL,
  "tahun" integer NOT NULL,
  "jumlah_hadir" integer DEFAULT 0,
  "jumlah_tidak_hadir" integer DEFAULT 0,
  "jumlah_telat" integer DEFAULT 0,
  "persentase_kehadiran" decimal(5,2),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "aturan_potongan" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "jenis_potongan" varchar(50) NOT NULL,
  "nominal_potongan" decimal(12,2) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "penggajian" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "bulan" integer NOT NULL,
  "tahun" integer NOT NULL,
  "gaji_pokok" decimal(12,2) DEFAULT 0,
  "tunjangan_kesehatan" decimal(12,2) DEFAULT 0,
  "tunjangan_transport" decimal(12,2) DEFAULT 0,
  "tunjangan_kerajinan" decimal(12,2) DEFAULT 0,
  "gaji_progress" decimal(12,2) DEFAULT 0,
  "total_potongan" decimal(12,2) DEFAULT 0,
  "total_gaji" decimal(12,2) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "detail_progress" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "penggajian_id" integer,
  "murid_id" integer,
  "kategori_murid_id" integer,
  "poin_didapat" decimal(8,2) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "detail_potongan" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "penggajian_id" integer,
  "aturan_potongan_id" integer,
  "jumlah_hari" integer NOT NULL,
  "total_potongan" decimal(12,2) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE UNIQUE INDEX ON "kehadiran" ("user_id", "bulan", "tahun");

CREATE UNIQUE INDEX ON "penggajian" ("user_id", "bulan", "tahun");

ALTER TABLE "users" ADD FOREIGN KEY ("unit_id") REFERENCES "units" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "murid" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "murid" ADD FOREIGN KEY ("unit_id") REFERENCES "units" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "murid" ADD FOREIGN KEY ("kategori_murid_id") REFERENCES "kategori_murid" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "kehadiran" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "penggajian" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detail_progress" ADD FOREIGN KEY ("penggajian_id") REFERENCES "penggajian" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detail_progress" ADD FOREIGN KEY ("murid_id") REFERENCES "murid" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detail_progress" ADD FOREIGN KEY ("kategori_murid_id") REFERENCES "kategori_murid" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detail_potongan" ADD FOREIGN KEY ("penggajian_id") REFERENCES "penggajian" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detail_potongan" ADD FOREIGN KEY ("aturan_potongan_id") REFERENCES "aturan_potongan" ("id") DEFERRABLE INITIALLY IMMEDIATE;
